schema_version: 1.0.0
version: 1
profile: guided
branch: main
versioning: semver
initial_tag: 0.0.7
commit_style: conventional-commits
semantic_release: false
actions:
    init: true
    branch: true
    stage: true
    commit: true
    tag: true
    remote: true
    push: true
remote:
    provider: github
    owner: averyfreeman
    name: dfrs
    visibility: public
    alias: origin
    status: configured
    url: https://github.com/averyfreeman/dfrs.git
